package com.example.smoothie;

import android.app.Application;
import toothpick.Configuration;
import toothpick.Scope;
import toothpick.Toothpick;
import toothpick.registries.FactoryRegistryLocator;
import toothpick.registries.MemberInjectorRegistryLocator;
import toothpick.smoothie.module.ToothpickApplicationModule;

public class SimpleApp extends Application {
  @Override
  public void onCreate() {
    super.onCreate();

    // com.example.smoothie.MemberInjectorRegistry and com.example.smoothie.FactoryRegistry are classes generated by this project
    // Your project will have these classes in your package (or the one you specify).
    // Please note that the fully qualified name should be used instead of an import.
    // (see https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries)
    // If you're not using the reflection free configuration, the next 3 lines can be omitted
    Configuration.setConfiguration(Configuration.reflectionFree());
    MemberInjectorRegistryLocator.setRootRegistry(new com.example.smoothie.MemberInjectorRegistry());
    FactoryRegistryLocator.setRootRegistry(new com.example.smoothie.FactoryRegistry());

    Scope appScope = Toothpick.openScope(this);
    appScope.installModules(new ToothpickApplicationModule(this));
  }
}