package toothpick.compiler;

/**
 * Common base interface for all code generators.
 */
public interface CodeGenerator {

  /**
   * Creates all java code.
   * @returns a string containing the java code generated by this {@link CodeGenerator}.
   */
  String brewJava();

  /**
   * @returns the FQN of the code generated by this {@link CodeGenerator}.
   */
  String getFqcn();
}
