/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'snicolas' at '3/24/16 3:48 AM' with Gradle 2.8
 *
 * @author snicolas, @date 3/24/16 3:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
